### ISSUE TITLE
没有docker版本吗[Feature Request] 

### ISSUE THREAD

**Issue by AlanWang2333** [LoCyan-Team/LoCyanFrpPureApp#4]
### Describe the feature request

我的设备是软路由，里面有docker

### Describe alternatives you've considered

linux的分支OpenWrt系统，里面有frp客户端，可惜不知道怎么填
![image](https://github.com/LoCyan-Team/LoCyanFrpPureApp/assets/58912611/5f0dfa10-add9-4ccf-bcb7-190e8381d400)

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by laobinghu** [comment]
+1
隔壁的openfrp都有官方的docker镜像
乐青的action好像配置有问题
能力可以的话建议自己编译（

**Comment by AlanWang2333** [comment]
> +1 隔壁的openfrp都有官方的docker镜像 乐青的action好像配置有问题 能力可以的话建议自己编译（

不会编译😂要不然就自己部署frpc了

**Comment by laobinghu** [comment]
乐青好像有frpc.ini可以导出来着

**Comment by AlanWang2333** [comment]
官网直接可以复制配置

**Comment by Muska-Ami** [comment]
没有Docker版本，需要请自行构建
